### ISSUE TITLE
Make the exec+args configuration more flexible

### ISSUE THREAD

**Issue by dmorn** [kim-company/pmux#3]
At the moment `pmux` spawns only process that fulfil its requirements, i.e.
- they accept the "--config" flag
- they accept the "--sock-path" flag

Basically the idea is that `pmux` is strict and the child process has to adapt - we want to reverse this and make `pmux` configurable.

**Comment by dmorn** [comment]
@philipgiuliani  do you remember the project we saw that was doing something similar with SQS?

**Comment by philipgiuliani** [comment]
https://github.com/corvus-ch/rabbitmq-cli-consumer here it is!

**Comment by dmorn** [comment]
Mmmmh actually it looks like we're happy with the current implementation 👍
